version: "3.5"
services:
  web3signer:
    image: "web3signer.web3signer.dnp.dappnode.eth:0.1.0"
    build:
      context: web3signer
      args:
        KEYFILES_DIR: /opt/web3signer/keyfiles
        KEYFILES_DIR_TMP: /opt/web3signer/keyfiles_tmp
    environment:
      KEYFILES_DIR: /opt/web3signer/keyfiles
      KEYFILES_DIR_TMP: /opt/web3signer/keyfiles_tmp
    ports:
      - "9003:9000"
    volumes:
      - "web3signer_keyfiles:/opt/web3signer/keyfiles"
      - "web3signer_keyfiles_tmp:/opt/web3signer/keyfiles_tmp"
    restart: unless-stopped
  postgres:
    build:
      context: postgres
    image: "postgres.web3signer.dnp.dappnode.eth:0.1.0"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: web3signer
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  web3signer_keyfiles: {}
  web3signer_keyfiles_tmp: {}
  postgres: {}
