version: "3.5"
services:
  brain:
    image: "brain.web3signer-gnosis.dnp.dappnode.eth:0.1.8"
    build:
      context: brain
    depends_on:
      - web3signer
    environment:
      - LOG_LEVEL=debug
    restart: unless-stopped
    volumes:
      - "brain_data:/app/data"
  web3signer:
    image: "web3signer.web3signer-gnosis.dnp.dappnode.eth:0.1.8"
    healthcheck:
      test: >-
        curl -H 'Host: web3signer.web3signer-prater.dappnode'
        http://localhost:9000/healthcheck
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - postgres
    security_opt:
      - "seccomp:unconfined"
    build:
      context: web3signer
      dockerfile: Dockerfile
      args:
        UPSTREAM_VERSION: 23.2.0
    environment:
      EXTRA_OPTS: ""
    volumes:
      - "web3signer_data:/data"
    restart: unless-stopped
  postgres:
    image: "postgres.web3signer-gnosis.dnp.dappnode.eth:0.1.8"
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
    build:
      context: postgres
      dockerfile: Dockerfile
      args:
        UPSTREAM_VERSION: 23.2.0
    user: postgres
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    restart: unless-stopped
volumes:
  brain_data: {}
  web3signer_data: {}
  postgres_data: {}
